extends Node
## Defs — loaded, read-only content definitions.
##
## All game content (commodities, hulls, modules, events, ...) lives in
## data/*.json and is loaded here at startup (via Content). Engine code reads
## these dictionaries; it never hard-codes content. Adding content = editing
## JSON, not touching this file.

const DATA_DIR := "res://data/"

## commodity id (String) -> definition (Dictionary: id, name, cargo_class, base_price)
var commodities: Dictionary = {}

## The star map as generated by tools/build_stars.py (credit, systems, lanes).
var stars: Dictionary = {}

## Content for World.create: known_planets, planet_types, archetypes,
## governments, names, balance (see Content.load_world_content).
var world_content: Dictionary = {}

func _ready() -> void:
	commodities = Content.load_list(DATA_DIR + "commodities.json")
	print("[Defs] loaded %d commodity definitions: %s" % [commodities.size(), ", ".join(commodities.keys())])
	stars = Content.load_object(DATA_DIR + "stars.json")
	print("[Defs] loaded %d star systems, %d lanes" % [
		stars.get("systems", []).size(), stars.get("lanes", []).size()])
	world_content = Content.load_world_content(DATA_DIR)
	print("[Defs] loaded %d known planet systems, %d archetypes, %d governments" % [
		world_content.known_planets.size(), world_content.archetypes.size(),
		world_content.governments.size()])

func archetype_name(id: String) -> String:
	return world_content.archetypes.get(id, {}).get("name", id)

func government_name(id: String) -> String:
	return world_content.governments.get(id, {}).get("name", id)

func planet_type(id: String) -> Dictionary:
	return world_content.planet_types.get(id, {})
