extends Node
## Defs — loaded, read-only content definitions.
##
## All game content (commodities, hulls, modules, events, ...) lives in
## data/*.json and is loaded here at startup. Engine code reads these
## dictionaries; it never hard-codes content. Adding content = editing JSON,
## not touching this file.

const DATA_DIR := "res://data/"

## commodity id (String) -> definition (Dictionary: id, name, cargo_class, base_price)
var commodities: Dictionary = {}

## The star map as generated by tools/build_stars.py (credit, systems, lanes).
## Build the sim's map with `Galaxy.from_dict(Defs.stars)`.
var stars: Dictionary = {}

func _ready() -> void:
	commodities = _load_json(DATA_DIR + "commodities.json")
	print("[Defs] loaded %d commodity definitions: %s" % [commodities.size(), ", ".join(commodities.keys())])
	stars = _load_object(DATA_DIR + "stars.json")
	print("[Defs] loaded %d star systems, %d lanes" % [
		stars.get("systems", []).size(), stars.get("lanes", []).size()])

## Loads a data file that is a single JSON object rather than a list of id'd
## entries (stars.json). Returns {} on any failure.
func _load_object(path: String) -> Dictionary:
	if not FileAccess.file_exists(path):
		push_error("[Defs] missing data file: %s" % path)
		return {}
	var parsed: Variant = JSON.parse_string(FileAccess.get_file_as_string(path))
	if not (parsed is Dictionary):
		push_error("[Defs] expected a JSON object at top level: %s" % path)
		return {}
	return parsed

## Loads a JSON file expected to contain an array of objects each with an "id"
## field, and returns a dictionary keyed by that id. Returns {} on any failure.
func _load_json(path: String) -> Dictionary:
	if not FileAccess.file_exists(path):
		push_error("[Defs] missing data file: %s" % path)
		return {}
	var parsed: Variant = JSON.parse_string(FileAccess.get_file_as_string(path))
	if parsed == null:
		push_error("[Defs] failed to parse JSON: %s" % path)
		return {}
	if not (parsed is Array):
		push_error("[Defs] expected a JSON array at top level: %s" % path)
		return {}
	var out: Dictionary = {}
	for entry in parsed:
		if entry is Dictionary and entry.has("id"):
			out[entry["id"]] = entry
		else:
			push_warning("[Defs] skipping entry without 'id' in %s" % path)
	return out
